name: Blog Action
on: [push, pull_request]
jobs:
  blog-action:
    name: blog-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Deployment Script
        uses: amitojsingh366/saakhi-blog-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # request-url: ${{ secrets.REQUEST_URL }}
          # authorization-secret: ${{ secrets.AUTHORIZATION_SECRET }}
          